///
/// @Generated by Mockolo
///

import Foundation
@testable import PBAuthInterface

public final class PBAuthLocalDataSourceMock: PBAuthLocalDataSource {
  public init() {}
  public init(accessToken: String? = nil, refreshToken: String? = nil) {
    self.accessToken = accessToken
    self.refreshToken = refreshToken
  }

  public private(set) var accessTokenSetCallCount = 0
  public var accessToken: String? = nil { didSet { accessTokenSetCallCount += 1 } }

  public private(set) var refreshTokenSetCallCount = 0
  public var refreshToken: String? = nil { didSet { refreshTokenSetCallCount += 1 } }
}
